### ISSUE TITLE
Workspace switcher cant find any workspaces since 1.10

### ISSUE THREAD

**Issue by sh-developers** [sadesyllas/vscode-workspace-switcher#18] opened 2019-03-25 08:45 UTC
Since upgrading to 1.10.x the extension can no longer locate my workspaces, I have not changed my config and had to disable Auto-update to revert to 1.9.0 to get it working again.

Tested non-working versions:
vscode-workspace-switcher: 1.10.3, 1.10.2
code: 1.32.3

Tested non-working versions (but not finding no workspaces, but instead not finding the command at all):
vscode-workspace-switcher: 1.10.1, 1.10.0

Working versions:
vscode-workspace-switcher: <= 1.9.0

My relevant config:
```json
{
    "vscodeWorkspaceSwitcher.paths": [
        "~/projects/services/*"
    ],
}
```

**Comment by noirbizarre** [comment] 2019-03-25 10:42
Same for me, globing isn't working anymore. Was working fine before.

**Comment by sadesyllas** [comment] 2019-03-26 12:20
The only recent, fs related change made, is the use of `stat` vs `lstat` for searching for `.code-workspace` files.

Can you please change `"~/projects/services/*"` to `"~/projects/services/**/"` and report whether or not this fixes the problem?

Eg, a working setup with the latest version is (working since the first support for globs was introduced):
```json
...,
"vscodeWorkspaceSwitcher.paths": [
    "~/VSCodeWorkspaces/**/"
],
...
```

**Comment by sadesyllas** [comment] 2019-03-26 12:26
Could it be that you are using sub-directories? If yes, then it could be as in #19 .

**Comment by sadesyllas** [comment] 2019-03-26 14:56
Please, try v1.10.4 report whether this has been fixed or not.

**Comment by noirbizarre** [comment] 2019-03-26 17:19
Not totally working:
- `~/Workspaces` works as expected (only root `.code-workspace` files)
- `~/Workspaces/**`  or `~/Workspaces/**/` only brings root workspaces
- `~/Workspaces/*` or `~/Workspaces/*/` only brings nested workspaces as expected
- `[~/Workspaces, ~/Workspaces/*]` works but brings duplicate root workspaces and nested workspaces are ok
- `[~/Workspaces, ~/Workspaces/**]` only brings root workspaces and in triple

Expected behavior is:
- `~/Workspaces` brings root workspaces only
- `~/Workspaces/*` only brings first level of nested workspaces
- `~/Workspaces/**` brings all workspaces, root and nested at any level
- `[~/Workspaces, ~/Workspaces/*]` only brings root and first nesting level workspaces

**Comment by sadesyllas** [comment] 2019-03-27 00:32
@noirbizarre thanks for your valuable insight!

I tried every case you mentioned and in v1.10.5 they all work, so please check and tell me if the problem is gone.

The only one I could not reproduce was the `~/Workspaces/**` as it has always worked for me.

**Comment by sh-developers** [comment] 2019-03-27 08:01
The 1.10.5-version works for my setup again. 1.11.0 breaks it again, and reverts to the issues of "1.10.1, 1.10.0" in that it keeps giving me the "command 'extension.switchWorkspaceNewWindow' not found"

**Comment by sadesyllas** [comment] 2019-03-27 08:20
I am closing this issue as the main topic of the issue has been solved and no new issues have come to my attention.

Please, re-open it or open another one in case something is wrong.

Thank you all for your help!

**Closed by sadesyllas** 2019-03-27 08:20 UTC
Labels: bug

**Comment by noirbizarre** [comment] 2019-03-27 10:14
I confirm that `1.11.0` fixed it. Thanks ! :pray:
